### ISSUE TITLE
Synthetic data convenient for performance scaling tests

### ISSUE THREAD

**Issue by heuermh** [NCBI-Hackathons/Bringing-the-Power-of-Synthetic-Data-Generation-to-the-Masses#8]
Thinking out loud here, from CoFest 2019, it might be nice to have synthetic data in sizes convenient for performance scaling tests, say factor-of-10 in both numbers of records and file size in Gb.

**Comment by vdauwera** [comment]
@heuermh I steered you wrong -- issues need to go in https://github.com/terra-workflows/synthetic-seq-data (didn't realize Issues weren't available there, just turned them on)

**Comment by heuermh** [comment]
Thanks!  Closing in favor of https://github.com/terra-workflows/synthetic-seq-data/issues/3
